name: CI - Weather Functions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          # installe en pointant vers le requirements du sous-dossier
          pip install -r api/BayrouMeter-functions/requirements.txt

      #- name: Run tests
      #  shell: bash
      #  run: |
      #    cd api/BayrouMeter-functions/
      #    pytest -q
